package net.revature.project1.enumerator;

public enum UserEnum {
    SUCCESS,
    UNAUTHORIZED,
    BAD_USERNAME,
    USERNAME_TAKEN,
    EMAIL_ALREADY_EXISTS,
    INVALID_EMAIL_FORMAT,
    USER_ALREADY_FOLLOWING,
    USER_ALREADY_FRIENDS,
    UNKNOWN,
    UNKNOWN_USER
}
